syntax = "proto3";

option go_package = "awesomeProject/proto";

package proto;

service Bank {
    rpc GetAccount(GetAccountRequest) returns (GetAccountResponse) {}
    rpc CreateAccount(CreateAccountRequest) returns (Empty) {}
    rpc PatchAccount(PatchAccountRequest) returns (Empty) {}
    rpc ChangeAccount(ChangeAccountRequest) returns (Empty) {}
    rpc DeleteAccount(DeleteAccountRequest) returns (Empty) {}
    rpc Transfer(TransferRequest) returns (TransferResponse) {}
}

message GetAccountRequest {
    string Name = 1;
}

message CreateAccountRequest {
    string Name = 1;
    int32 Amount = 2;
}

message PatchAccountRequest {
    string Name = 1;
    int32 Amount = 2;
}

message ChangeAccountRequest {
    string Name = 1;
    string New_name = 2;
}

message DeleteAccountRequest {
    string Name = 1;
}

message GetAccountResponse {
    string Name = 1;
    int32 Amount = 2;
}

message TransferRequest {
    string Sender_name = 1;
    string Receiver_name = 2;
    int64 Amount = 3;
}

message TransferResponse {
    int64 Fee = 1;
    int64 Sender_balance = 2;
    int64 Receiver_balance = 3;
}

message Empty {

}
